import { checkAdminRequest, recordAdminAudit } from "@/lib/api";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { matchInput } from "@/lib/validation";
import { isCompetition } from "@/lib/sports/competitions";

const privateHeaders = { "cache-control": "private, no-store" };

/**
 * Admin → Schedule listing.
 *
 * Returns every match (published or not) ordered by date and kickoff time so the
 * console can group them into today / tomorrow / future and offer search,
 * filtering, edit, delete, publish and duplicate actions.
 */
export async function GET(request: Request) {
  const access = await checkAdminRequest(request, "admin-matches-read");
  if (access.response) return access.response;
  const client = await createSupabaseServerClient();
  if (!client) return Response.json({ error: "Database is not configured." }, { status: 503 });

  const query = new URL(request.url).searchParams;
  const search = query.get("search")?.trim();

  let request_ = client
    .from("matches")
    .select("*")
    .order("match_date", { ascending: true })
    .order("kickoff_time", { ascending: true })
    .order("created_at", { ascending: true })
    .range(0, 999);

  if (search) {
    // Strip PostgREST filter syntax so a search term cannot break the query.
    const escaped = search.replace(/[%,()]/g, " ").trim();
    if (escaped) {
      request_ = request_.or(
        `home_team.ilike.%${escaped}%,away_team.ilike.%${escaped}%,competition.ilike.%${escaped}%,fixture_id.ilike.%${escaped}%`,
      );
    }
  }

  const { data, error } = await request_;
  if (error) return Response.json({ error: "Could not load matches." }, { status: 500 });
  return Response.json({ data }, { headers: privateHeaders });
}

/**
 * Creates a manually entered match.
 *
 * The internal fixture ID is generated by the database
 * (`public.generate_match_fixture_id`) from the match date, for example
 * ML-20261007-0001. Nothing here depends on an external fixture provider.
 */
export async function POST(request: Request) {
  const access = await checkAdminRequest(request, "admin-matches-write", 30);
  if (access.response) return access.response;
  const parsed = matchInput.safeParse(await request.json().catch(() => null));
  if (!parsed.success) {
    return Response.json({ error: "Invalid match fields.", details: parsed.error.flatten() }, { status: 400 });
  }
  if (!isCompetition(parsed.data.competition)) {
    return Response.json({ error: "Choose one of the supported competitions." }, { status: 400 });
  }

  const client = await createSupabaseServerClient();
  if (!client) return Response.json({ error: "Database is not configured." }, { status: 503 });
  const { data: { user } } = await client.auth.getUser();
  if (!user) return Response.json({ error: "Administrator session expired." }, { status: 401 });

  const { data: fixtureId, error: idError } = await client
    .rpc("generate_match_fixture_id", { target_date: parsed.data.match_date });
  if (idError || !fixtureId) {
    return Response.json({ error: "Could not generate a fixture ID." }, { status: 500 });
  }

  const { data, error } = await client
    .from("matches")
    .insert({ ...parsed.data, fixture_id: fixtureId, created_by: user.id })
    .select("*")
    .single();
  if (error) return Response.json({ error: "Could not create the match." }, { status: 400 });

  await recordAdminAudit("create", "match", data.fixture_id, {
    match_date: data.match_date,
    competition: data.competition,
  });
  return Response.json({ data }, { status: 201, headers: privateHeaders });
}